/* Bundle the explicit ESM graph into the single file required by Figma. */
'use strict';

const esbuild = require('esbuild') as typeof import('esbuild');
const fs = require('node:fs') as typeof import('node:fs');
const path = require('node:path') as typeof import('node:path');
const vm = require('node:vm') as typeof import('node:vm');
const { errorStack } = require('../core/errors.ts') as {
  errorStack(error: unknown): string;
};

export const PLUGIN_ROOT = path.resolve(__dirname, '..', '..');
export const SOURCE_ROOT = path.join(PLUGIN_ROOT, 'src');
export const BUNDLE_ENTRY = path.join(SOURCE_ROOT, 'plugin', 'entry.ts');
export const BUNDLE_FILE = path.join(PLUGIN_ROOT, 'code.js');
/** The IIFE global through which the offline harness reaches HARNESS_API. */
export const BUNDLE_GLOBAL_NAME = 'FigmaHarnessPlugin';

export interface PluginBundle {
  code: Buffer;
  modules: string[];
  unreachable: string[];
}

function failure(message: string, cause: unknown): Error {
  return Object.assign(new Error(message + '\n' + errorStack(cause)), { cause });
}

function walkTypeScript(directory: string, prefix: string): string[] {
  const files: string[] = [];
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const relative = prefix ? path.posix.join(prefix, entry.name) : entry.name;
    if (entry.isDirectory()) {
      files.push(...walkTypeScript(path.join(directory, entry.name), relative));
    } else if (entry.isFile() && entry.name.endsWith('.ts')) {
      files.push(relative);
    }
  }
  return files.sort();
}

/** Bundle src/ in memory. Throws with a readable reason when the graph is invalid. */
export function bundlePlugin(): PluginBundle {
  let result: import('esbuild').BuildResult;
  try {
    result = esbuild.buildSync({
      absWorkingDir: PLUGIN_ROOT,
      entryPoints: [BUNDLE_ENTRY],
      bundle: true,
      charset: 'utf8',
      format: 'iife',
      globalName: BUNDLE_GLOBAL_NAME,
      legalComments: 'inline',
      metafile: true,
      minify: false,
      outfile: BUNDLE_FILE,
      platform: 'browser',
      target: ['es2020'],
      treeShaking: false,
      write: false,
      banner: {
        js: '/* @generated by tools/runtime/build.ts — do not edit; run npm run build. */',
      },
    });
  } catch (error: unknown) {
    throw failure('bundling failed', error);
  }

  const outputFiles = result.outputFiles;
  const output = outputFiles?.find((file) => file.path === BUNDLE_FILE) || outputFiles?.[0];
  if (!output) throw new Error('esbuild produced no JavaScript output');

  // Normalize whitespace inside preserved block comments before parity checks.
  const code = Buffer.from(output.text.replace(/[ \t]+$/gm, ''));
  try {
    new vm.Script(code.toString('utf8'), { filename: 'code.js' });
  } catch (error: unknown) {
    throw failure('generated JavaScript is invalid', error);
  }

  if (!result.metafile) throw new Error('esbuild produced no dependency metafile');
  const modules = walkTypeScript(SOURCE_ROOT, '');
  const bundled = new Set(Object.keys(result.metafile.inputs).map((file) =>
    path.relative(SOURCE_ROOT, path.resolve(PLUGIN_ROOT, file)).split(path.sep).join('/')));
  return {
    code,
    modules,
    unreachable: modules.filter((file) => !bundled.has(file)),
  };
}
