/* Component families that must be documented on a design-system sheet.
 * Each family is recognised by the node names its builder emits. */

export const COMPONENT_INVENTORY: ReadonlyArray<readonly [family: string, nodeName: RegExp]> = Object.freeze([
  ['Button', /^button\//],
  ['IconButton', /^icon-button\//],
  ['Label', /^label\//],
  ['StateLabel', /^state-label\//],
  ['CounterLabel', /^counter$/],
  ['Token', /^token\//],
  ['BranchName', /^branch\//],
  ['Avatar', /^avatar$/],
  ['AvatarStack', /^avatar-stack$/],
  ['TextInput', /^text-input$/],
  ['Select', /^select$/],
  ['Textarea', /^textarea$/],
  ['FormControl', /^form-control$/],
  ['Checkbox', /^checkbox$/],
  ['Radio', /^radio$/],
  ['ToggleSwitch', /^toggle-switch$/],
  ['SegmentedControl', /^segmented-control$/],
  ['ActionList', /^action-list$/],
  ['NavList', /^nav-list$/],
  ['UnderlineNav', /^underline-nav$/],
  ['Breadcrumbs', /^breadcrumbs$/],
  ['Pagination', /^pagination$/],
  ['Banner', /^banner\//],
  ['Blankslate', /^blankslate$/],
  ['InlineMessage', /^inline-message\//],
  ['ProgressBar', /^progress-bar$/],
  ['Timeline', /^timeline$/],
  ['Dialog', /^dialog$/],
  ['Tooltip', /^tooltip$/],
  ['Spinner', /^spinner$/],
  ['Box', /^box$/],
  ['PageHeader', /^page-header$/],
  ['DataTable', /^data-table$/],
] as const);
