/* GENERATED by packages/harness/src/accessibility/cvd-table.ts — do not edit. Run: pnpm cvd:generate templates/design-system */

export const CVD = {
  "protanopia": {
    "status/positive": "#6E6E66",
    "status/warning": "#61610D",
    "status/critical": "#50505B",
    "accent/default": "#5757D0"
  },
  "deuteranopia": {
    "status/positive": "#636367",
    "status/warning": "#6B6B00",
    "status/critical": "#737355",
    "accent/default": "#5151D0"
  },
  "tritanopia": {
    "status/positive": "#5555D2",
    "status/warning": "#757500",
    "status/critical": "#909000",
    "accent/default": "#4949EF"
  },
  "normal": {
    "status/positive": "#0D7466",
    "status/warning": "#8A5A0B",
    "status/critical": "#C2285A",
    "accent/default": "#2D5BD0"
  },
  "ratios": {
    "text/default on surface/page": 15.9,
    "text/muted on surface/page": 6.06,
    "focus/ring on surface/page": 5.97,
    "border/control on surface/page": 3.72
  }
};
/** The ratio a sheet may print, formatted. Never type one by hand. */
const ratioLabel = function (a: string, b: string): string { const ratios = CVD.ratios as Readonly<Record<string, number>>; const value = ratios[a + ' on ' + b]; return value == null ? '—' : value.toFixed(2) + ':1'; };
export { ratioLabel as R };
