/* GENERATED by packages/harness/src/accessibility/cvd-table.ts — do not edit. Run: pnpm cvd:generate */

export const CVD = {
  "protanopia": {
    "bgColor/neutral-emphasis": "#62626E",
    "bgColor/accent-emphasis": "#6363DA",
    "bgColor/success-emphasis": "#81813C",
    "bgColor/attention-emphasis": "#6E6E02",
    "bgColor/severe-emphasis": "#616106",
    "bgColor/danger-emphasis": "#525230",
    "bgColor/done-emphasis": "#5757DF"
  },
  "deuteranopia": {
    "bgColor/neutral-emphasis": "#60606E",
    "bgColor/accent-emphasis": "#5959DA",
    "bgColor/success-emphasis": "#757540",
    "bgColor/attention-emphasis": "#797900",
    "bgColor/severe-emphasis": "#7B7B00",
    "bgColor/danger-emphasis": "#7A7A1F",
    "bgColor/done-emphasis": "#6262DF"
  },
  "tritanopia": {
    "bgColor/neutral-emphasis": "#5E5E84",
    "bgColor/accent-emphasis": "#4C4CFF",
    "bgColor/success-emphasis": "#6666E0",
    "bgColor/attention-emphasis": "#838300",
    "bgColor/severe-emphasis": "#919100",
    "bgColor/danger-emphasis": "#989800",
    "bgColor/done-emphasis": "#6C6C97"
  },
  "normal": {
    "bgColor/neutral-emphasis": "#59636E",
    "bgColor/accent-emphasis": "#0969DA",
    "bgColor/success-emphasis": "#1F883D",
    "bgColor/attention-emphasis": "#9A6700",
    "bgColor/severe-emphasis": "#BC4C00",
    "bgColor/danger-emphasis": "#CF222E",
    "bgColor/done-emphasis": "#8250DF"
  },
  "ratios": {
    "fgColor/default on bgColor/default": 15.8,
    "fgColor/muted on bgColor/default": 6.11,
    "fgColor/muted on bgColor/muted": 5.74,
    "fgColor/link on bgColor/default": 5.19,
    "focus/outline-color on bgColor/default": 5.19,
    "focus/outline-color on button/default/bgColor/rest": 4.88,
    "focus/outline-color on fgColor/onEmphasis": 5.19,
    "control/borderColor/emphasis on bgColor/default": 3.45,
    "control/borderColor/rest on bgColor/default": 1.43,
    "underlineNav/borderColor/active on bgColor/default": 2.29,
    "button/primary/fgColor/rest on button/primary/bgColor/rest": 4.52,
    "bgColor/default on bgColor/muted": 1.06,
    "bgColor/muted on control/bgColor/hover": 1.06,
    "control/bgColor/hover on control/bgColor/active": 1.08,
    "control/bgColor/active on controlTrack/bgColor/hover": 1.04,
    "controlTrack/bgColor/hover on controlTrack/bgColor/active": 1.06,
    "controlTrack/bgColor/active on borderColor/default": 1.07
  }
};
/** The ratio a sheet may print, formatted. Never type one by hand. */
const ratioLabel = function (a: string, b: string): string { const ratios = CVD.ratios as Readonly<Record<string, number>>; const value = ratios[a + ' on ' + b]; return value == null ? '—' : value.toFixed(2) + ':1'; };
export { ratioLabel as R };
