/* GENERATED by packages/harness/src/accessibility/cvd-table.ts — do not edit. Run: pnpm cvd:generate design-systems/carrara */

export const CVD = {
  "protanopia": {
    "status/positive": "#696941",
    "status/warning": "#606002",
    "status/critical": "#4E4E3C",
    "accent/solid": "#4747E5",
    "chart/secondary": "#8B8B99"
  },
  "deuteranopia": {
    "status/positive": "#5F5F43",
    "status/warning": "#686800",
    "status/critical": "#727232",
    "accent/solid": "#4949E5",
    "chart/secondary": "#8A8A99"
  },
  "tritanopia": {
    "status/positive": "#5252BD",
    "status/warning": "#717100",
    "status/critical": "#8E8E00",
    "accent/solid": "#4B4BDE",
    "chart/secondary": "#8989A8"
  },
  "normal": {
    "status/positive": "#156F41",
    "status/warning": "#835A00",
    "status/critical": "#C1253B",
    "accent/solid": "#4F46E5",
    "chart/secondary": "#868C99"
  },
  "ratios": {
    "text/primary on bg/surface": 17.78,
    "text/secondary on bg/surface": 7.76,
    "text/tertiary on bg/subtle": 5.02,
    "border/control on bg/canvas": 3.17,
    "focus/ring on bg/surface": 4.47,
    "focus/ring on bg/inverse": 4.29,
    "text/inverse on bg/inverse": 13.15
  }
};
/** The ratio a sheet may print, formatted. Never type one by hand. */
const ratioLabel = function (a: string, b: string): string { const ratios = CVD.ratios as Readonly<Record<string, number>>; const value = ratios[a + ' on ' + b]; return value == null ? '—' : value.toFixed(2) + ':1'; };
export { ratioLabel as R };
