import { BRAND_GLYPHS, OCTICONS } from './catalog.ts';

const fs = require('node:fs') as typeof import('node:fs');
const path = require('node:path') as typeof import('node:path');

export const ICON_HEIGHTS = Object.freeze([12, 16, 24] as const);

export interface IconGeneration {
  /** Octicon name -> design height -> the glyph's path elements. */
  icons: Record<string, Record<number, string>>;
  version: string;
}

const ALLOWED_ATTRIBUTES = new Set(['d', 'fill-rule', 'clip-rule']);

/** An Octicon's path elements, verbatim, after proving they are nothing else. */
export function glyphPaths(svg: string, label: string): string {
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>[\s\S]*$/, '').trim();
  const elements = inner.match(/<[^>]+>/g) || [];
  if (!elements.length) throw new Error(label + ' has no path');
  for (const element of elements) {
    if (!/^<path\b[^>]*\/>$/.test(element)) throw new Error(label + ' contains ' + element.slice(0, 40));
    for (const [, name] of element.matchAll(/\s([a-z-]+)="/g)) {
      if (!ALLOWED_ATTRIBUTES.has(name)) throw new Error(label + ' uses the attribute ' + name);
    }
  }
  if (inner.replace(/<path\b[^>]*\/>/g, '').trim()) throw new Error(label + ' has content outside its paths');
  return elements.join('');
}

export function loadOcticons(packageRoot: string): IconGeneration {
  const version = (JSON.parse(fs.readFileSync(path.join(packageRoot, 'package.json'), 'utf8')) as { version: string }).version;
  const directory = path.join(packageRoot, 'build', 'svg');
  const icons: Record<string, Record<number, string>> = {};
  const missing: string[] = [];
  for (const name of OCTICONS) {
    if (BRAND_GLYPHS.test(name)) throw new Error(name + ' is a GitHub mark, not an icon');
    const heights: Record<number, string> = {};
    for (const height of ICON_HEIGHTS) {
      const filename = path.join(directory, name + '-' + height + '.svg');
      if (!fs.existsSync(filename)) continue;
      const svg = fs.readFileSync(filename, 'utf8');
      if (!svg.includes('viewBox="0 0 ' + height + ' ' + height + '"')) {
        throw new Error(name + '-' + height + ' is not drawn on a square ' + height + ' px grid');
      }
      heights[height] = glyphPaths(svg, name + '-' + height);
    }
    if (!heights[16]) missing.push(name);
    icons[name] = heights;
  }
  if (missing.length) throw new Error('Octicons without a 16 px glyph: ' + missing.join(', '));
  if (new Set(OCTICONS).size !== OCTICONS.length) throw new Error('an icon is listed twice');
  return { icons, version };
}

export function formatIconModule(generation: IconGeneration): string {
  const quote = (value: string) => "'" + value.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
  const lines = Object.keys(generation.icons).sort().map((name) => {
    const heights = generation.icons[name];
    const entries = Object.keys(heights).map((height) => height + ': ' + quote(heights[Number(height)]));
    return '  ' + quote(name) + ': { ' + entries.join(', ') + ' },';
  });
  return [
    '/* GENERATED by generators/icons/icons.ts from @primer/octicons v' + generation.version + ' (MIT, GitHub Inc.).',
    ' * Do not edit by hand. Run: pnpm icons:generate */',
    '',
    "export const OCTICONS_VERSION = '" + generation.version + "';",
    '',
    '/** Octicon name -> design height -> filled path elements. */',
    'export const ICONS = {',
    ...lines,
    '} as const;',
    '',
  ].join('\n');
}
