/* Bundle the explicit ESM graph into the single file required by Figma. */
'use strict';

import { bundledPackages, pluginLayout, repositoryRoot } from '../core/workspace.ts';

const esbuild = require('esbuild') as typeof import('esbuild');
const fs = require('node:fs') as typeof import('node:fs');
const path = require('node:path') as typeof import('node:path');
const vm = require('node:vm') as typeof import('node:vm');
const { errorStack } = require('../core/errors.ts') as {
  errorStack(error: unknown): string;
};
/** The IIFE global through which the offline harness reaches HARNESS_API. */
export const BUNDLE_GLOBAL_NAME = 'FigmaHarnessPlugin';

export interface PluginBundle {
  code: Buffer;
  /** Every bundled workspace source file, relative to the repository root. */
  modules: string[];
  unreachable: string[];
}

/** The committed bundle Figma loads. */
export function bundleFile(): string {
  return pluginLayout().bundle;
}

function failure(message: string, cause: unknown): Error {
  return Object.assign(new Error(message + '\n' + errorStack(cause)), { cause });
}

function walkTypeScript(directory: string, prefix: string): string[] {
  const files: string[] = [];
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const relative = prefix ? path.posix.join(prefix, entry.name) : entry.name;
    if (entry.isDirectory()) {
      files.push(...walkTypeScript(path.join(directory, entry.name), relative));
    } else if (entry.isFile() && entry.name.endsWith('.ts')) {
      files.push(relative);
    }
  }
  return files.sort();
}

/** Bundle the plugin in memory. Throws with a readable reason when the graph is invalid. */
export function bundlePlugin(): PluginBundle {
  const root = repositoryRoot();
  const layout = pluginLayout(root);
  let result: import('esbuild').BuildResult;
  try {
    result = esbuild.buildSync({
      absWorkingDir: root,
      entryPoints: [layout.entry],
      bundle: true,
      charset: 'utf8',
      format: 'iife',
      globalName: BUNDLE_GLOBAL_NAME,
      legalComments: 'inline',
      metafile: true,
      minify: false,
      outfile: layout.bundle,
      platform: 'browser',
      target: ['es2020'],
      treeShaking: false,
      write: false,
      banner: {
        js: '/* @generated by packages/harness/src/bundle/build.ts — do not edit; run pnpm build. */',
      },
    });
  } catch (error: unknown) {
    throw failure('bundling failed', error);
  }

  const outputFiles = result.outputFiles;
  const output = outputFiles?.find((file) => file.path === layout.bundle) || outputFiles?.[0];
  if (!output) throw new Error('esbuild produced no JavaScript output');

  // Normalize whitespace inside preserved block comments before parity checks.
  const code = Buffer.from(output.text.replace(/[ \t]+$/gm, ''));
  try {
    new vm.Script(code.toString('utf8'), { filename: 'code.js' });
  } catch (error: unknown) {
    throw failure('generated JavaScript is invalid', error);
  }

  if (!result.metafile) throw new Error('esbuild produced no dependency metafile');
  const relative = (file: string): string => path.relative(root, file).split(path.sep).join('/');
  const modules = bundledPackages(root).flatMap((entry) => {
    const sources = path.join(entry.dir, 'src');
    return fs.existsSync(sources)
      ? walkTypeScript(sources, '').map((file) => relative(path.join(sources, file)))
      : [];
  });
  const bundled = new Set(Object.keys(result.metafile.inputs).map((file) =>
    relative(fs.realpathSync(path.resolve(root, file)))));
  return {
    code,
    modules,
    unreachable: modules.filter((file) => !bundled.has(file)),
  };
}
