/* Bundle the explicit ESM graph into the single file required by Figma. */
'use strict';

import {
  ACTIVE_APP_SPECIFIER,
  ACTIVE_DESIGN_SYSTEM_SPECIFIER,
  activeComposition,
  appDesignSystem,
  bundledPackages,
  exportedFile,
  pluginLayout,
  repositoryRoot,
} from '../core/workspace.ts';

const esbuild = require('esbuild') as typeof import('esbuild');
const fs = require('node:fs') as typeof import('node:fs');
const path = require('node:path') as typeof import('node:path');
const vm = require('node:vm') as typeof import('node:vm');
const { errorStack } = require('../core/errors.ts') as {
  errorStack(error: unknown): string;
};
/** The IIFE global through which the offline harness reaches HARNESS_API. */
export const BUNDLE_GLOBAL_NAME = 'FigmaHarnessPlugin';

export interface BundleOptions {
  /** The app to compose; the active app by default. */
  app?: string;
  /** Build the app with this design system instead of the one it depends on. */
  designSystem?: string;
  /** Bundle this module instead of the plugin entry, so a test can load it
   *  without Figma. Its exports appear on the bundle global. */
  entry?: string;
}

export interface PluginBundle {
  code: Buffer;
  /** Every bundled workspace source file, relative to the repository root. */
  modules: string[];
  unreachable: string[];
}

/** The committed bundle Figma loads. */
export function bundleFile(): string {
  return pluginLayout().bundle;
}

const BANNER = /^\/\* @generated by \S+ for (\S+) with (\S+) — /;

/** The app and design system a bundle was built for, read from its first line. */
export function bundledComposition(code: string): { app: string; designSystem: string } | null {
  const match = BANNER.exec(code);
  return match ? { app: match[1], designSystem: match[2] } : null;
}

/** Replace the committed bundle in one step, so Figma never loads half a file. */
export function writeBundle(bundle: PluginBundle): void {
  const file = bundleFile();
  const temporary = file + '.tmp';
  fs.writeFileSync(temporary, bundle.code);
  fs.renameSync(temporary, file);
}

function failure(message: string, cause: unknown): Error {
  return Object.assign(new Error(message + '\n' + errorStack(cause)), { cause });
}

function walkTypeScript(directory: string, prefix: string): string[] {
  const files: string[] = [];
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const relative = prefix ? path.posix.join(prefix, entry.name) : entry.name;
    if (entry.isDirectory()) {
      files.push(...walkTypeScript(path.join(directory, entry.name), relative));
    } else if (entry.isFile() && entry.name.endsWith('.ts')) {
      files.push(relative);
    }
  }
  return files.sort();
}

/** Bundle the plugin with one app and its design system, in memory. Throws
 *  with a readable reason when the graph is invalid. */
export function bundlePlugin(options: BundleOptions = {}): PluginBundle {
  const root = repositoryRoot();
  const layout = pluginLayout(root);
  const composition = activeComposition(root, options.app, options.designSystem);
  const alias: Record<string, string> = {
    [ACTIVE_APP_SPECIFIER]: exportedFile(composition.app, '.'),
    [ACTIVE_DESIGN_SYSTEM_SPECIFIER]: exportedFile(composition.designSystem, './system'),
  };
  if (composition.substituted) {
    // The app's own imports of its design system reach the substitute instead.
    alias[appDesignSystem(composition.app, root).name] = exportedFile(composition.designSystem, '.');
  }
  let result: import('esbuild').BuildResult;
  try {
    result = esbuild.buildSync({
      absWorkingDir: root,
      entryPoints: [options.entry || layout.entry],
      // The plugin composes whatever these aliases point at.
      alias,
      bundle: true,
      charset: 'utf8',
      format: 'iife',
      globalName: BUNDLE_GLOBAL_NAME,
      legalComments: 'inline',
      metafile: true,
      minify: false,
      outfile: layout.bundle,
      platform: 'browser',
      target: ['es2020'],
      treeShaking: false,
      write: false,
      // The first line names the composition, so a stale code.js is caught before it is audited.
      banner: {
        js: '/* @generated by packages/harness/src/bundle/build.ts for ' + composition.app.relative
          + ' with ' + composition.designSystem.relative + ' — do not edit; run pnpm build. */',
      },
    });
  } catch (error: unknown) {
    throw failure('bundling ' + composition.app.relative + ' with ' + composition.designSystem.relative + ' failed'
      + (composition.substituted ? ' (only the app template is written for every design system)' : ''), error);
  }

  const outputFiles = result.outputFiles;
  const output = outputFiles?.find((file) => file.path === layout.bundle) || outputFiles?.[0];
  if (!output) throw new Error('esbuild produced no JavaScript output');

  // Normalize whitespace inside preserved block comments before parity checks.
  const code = Buffer.from(output.text.replace(/[ \t]+$/gm, ''));
  try {
    new vm.Script(code.toString('utf8'), { filename: 'code.js' });
  } catch (error: unknown) {
    throw failure('generated JavaScript is invalid', error);
  }

  if (!result.metafile) throw new Error('esbuild produced no dependency metafile');
  const relative = (file: string): string => path.relative(root, file).split(path.sep).join('/');
  const modules = bundledPackages(root, options.app, options.designSystem).flatMap((entry) => {
    const sources = path.join(entry.dir, 'src');
    return fs.existsSync(sources)
      ? walkTypeScript(sources, '').map((file) => relative(path.join(sources, file)))
      : [];
  });
  const bundled = new Set(Object.keys(result.metafile.inputs).map((file) =>
    relative(fs.realpathSync(path.resolve(root, file)))));
  return {
    code,
    modules,
    unreachable: modules.filter((file) => !bundled.has(file)),
  };
}
