/* Read the pinned Heroicons package: the solid glyphs, drawn on 16 and 20 px
 * grids, as path elements only. */

import { HEROICONS } from './catalog.ts';

const fs = require('node:fs') as typeof import('node:fs');
const path = require('node:path') as typeof import('node:path');

export const ICON_GRIDS = Object.freeze([16, 20] as const);

export interface IconSet {
  /** Heroicons name -> grid -> the glyph's path elements. */
  readonly icons: Record<string, Record<number, string>>;
  readonly version: string;
}

const KEPT_ATTRIBUTES = new Set(['d', 'fill-rule', 'clip-rule']);

/* A glyph's paths, with the attributes that only describe the source file removed. */
const pathsOf = function (svg: string, label: string): string {
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>[\s\S]*$/, '').trim();
  const elements = inner.match(/<[^>]+>/g) || [];
  if (!elements.length) throw new Error(label + ' has no path');
  const paths = elements.map((element) => {
    if (!/^<path\b[^>]*\/>$/.test(element)) throw new Error(label + ' contains ' + element.slice(0, 40));
    const attributes = [...element.matchAll(/\s([a-z-]+)="([^"]*)"/g)];
    for (const [, name] of attributes) {
      if (!KEPT_ATTRIBUTES.has(name)) throw new Error(label + ' uses the attribute ' + name);
    }
    return '<path ' + attributes.map(([, name, value]) => name + '="' + value + '"').join(' ') + '/>';
  });
  if (inner.replace(/<path\b[^>]*\/>/g, '').trim()) throw new Error(label + ' has content outside its paths');
  return paths.join('');
};

export function loadHeroicons(packageRoot: string): IconSet {
  const manifest = JSON.parse(fs.readFileSync(path.join(packageRoot, 'package.json'), 'utf8')) as { version: string };
  const icons: Record<string, Record<number, string>> = {};
  if (new Set(HEROICONS).size !== HEROICONS.length) throw new Error('an icon is listed twice');
  for (const name of HEROICONS) {
    const grids: Record<number, string> = {};
    for (const grid of ICON_GRIDS) {
      const filename = path.join(packageRoot, String(grid), 'solid', name + '.svg');
      if (!fs.existsSync(filename)) throw new Error(name + ' has no ' + grid + ' px solid glyph');
      const svg = fs.readFileSync(filename, 'utf8');
      if (!svg.includes('viewBox="0 0 ' + grid + ' ' + grid + '"')) {
        throw new Error(name + '-' + grid + ' is not drawn on a square ' + grid + ' px grid');
      }
      grids[grid] = pathsOf(svg, name + '-' + grid);
    }
    icons[name] = grids;
  }
  return { icons, version: manifest.version };
}

export function formatIconModule(set: IconSet): string {
  const literal = (value: string) => "'" + value.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
  const rows = Object.keys(set.icons).sort().map((name) => {
    const grids = set.icons[name];
    return '  ' + literal(name) + ': { ' + Object.keys(grids).map((grid) => grid + ': ' + literal(grids[Number(grid)])).join(', ') + ' },';
  });
  return [
    '/*! GENERATED by generators/icons/icons.ts from heroicons v' + set.version + '.',
    ' * Heroicons: Copyright (c) Tailwind Labs, Inc. MIT License, reproduced in design-systems/carrara/NOTICE.md.',
    ' * Do not edit by hand. Run: pnpm generate */',
    '',
    "export const HEROICONS_VERSION = '" + set.version + "';",
    '',
    'export const ICONS = {',
    ...rows,
    '} as const;',
    '',
  ].join('\n');
}
