/* Component families that must appear on a documentation sheet, recognised
 * by the layer names their builders emit. */

export const COMPONENT_INVENTORY: ReadonlyArray<readonly [family: string, nodeName: RegExp]> = Object.freeze([
  ['Button', /^button\//],
  ['IconButton', /^icon-button\//],
  ['Badge', /^badge\//],
  ['Trend', /^trend\//],
  ['Field', /^field\//],
  ['Checkbox', /^checkbox\//],
  ['Switch', /^switch\//],
  ['Tabs', /^tabs$/],
  ['Segmented', /^segmented$/],
  ['Card', /^card$/],
  ['Stat', /^stat\//],
  ['Table', /^table$/],
  ['Pagination', /^pagination$/],
  ['Alert', /^alert\//],
  ['Toast', /^toast$/],
  ['Progress', /^progress\//],
  ['BarList', /^bar-list$/],
  ['Timeline', /^timeline$/],
  ['DescriptionList', /^description-list$/],
  ['FactStrip', /^fact-strip$/],
  ['Menu', /^menu$/],
  ['Dialog', /^dialog\//],
  ['ListRow', /^list-row\//],
  ['EmptyState', /^empty-state$/],
  ['Avatar', /^avatar$/],
  ['Chart', /^chart\//],
  ['Sidebar', /^sidebar$/],
  ['Topbar', /^topbar$/],
  ['PageHeader', /^page-header$/],
]);
