/* ============================================================================
 * Generates src/kit/foundations/cvd.generated.ts: what each declared colour
 * looks like to a reader with colour-vision deficiency.
 *
 * The plugin runs inside Figma and cannot require tools/color/core/color.ts,
 * and a second Viénot reduction in src/ would mean two implementations of the
 * same physics, quietly disagreeing. So the values are computed here, once,
 * and emitted as a table. tools/accessibility/a11y.ts re-derives them on every
 * run and fails if the table has drifted.
 * ==========================================================================*/
'use strict';

import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  flatten,
  ratio,
  simulate,
  toHex,
} from '../color/core/color.ts';
import { CVD_KINDS } from '../color/core/palette-analysis.ts';
import { colorTokenMap } from '../color/core/token-values.ts';
import type { DesignSystemContract } from '../runtime/harness/contract.ts';

interface CvdColor {
  readonly a?: number;
  readonly b: number;
  readonly g: number;
  readonly r: number;
}

/* Sheets quote ratios as they appear on the light page. */
const PAGE = Object.freeze({ r: 255, g: 255, b: 255 });

export type CvdColorMap = Readonly<Record<string, CvdColor>>;

export const KINDS = CVD_KINDS;

/** Simulate the declared colours; the design system also names the ratios its sheets quote. */
export async function table(colors?: CvdColorMap, contract?: DesignSystemContract['cvd']): Promise<
  Record<string, Record<string, string | number>> & {
    normal: Record<string, string>;
    ratios: Record<string, number>;
  }
> {
  let V = colors;
  let cvd = contract;
  if (!V || !cvd) {
    const { createHarness } = await import('../runtime/harness.ts');
    const harness = createHarness();
    cvd = cvd || harness.runtime.CONTRACT.designSystem.cvd;
    if (!V) {
      await harness.runtime.ensureTokens();
      V = colorTokenMap(harness.vars);
    }
  }
  const SHOW = cvd.show;
  const QUOTED = cvd.quoted;
  const out = {} as Record<string, Record<string, string | number>> & {
    normal: Record<string, string>;
    ratios: Record<string, number>;
  };
  const shown = (token: string) => flatten(V![token], PAGE);
  for (const k of KINDS) {
    out[k] = {};
    for (const t of SHOW) if (V[t]) out[k][t] = toHex(simulate(shown(t), k));
  }
  out.normal = {};
  for (const t of SHOW) if (V[t]) out.normal[t] = toHex(shown(t));
  out.ratios = {};
  for (const [a, b] of QUOTED) {
    if (!V[a] || !V[b]) continue;
    const ground = shown(b);
    out.ratios[a + ' on ' + b] = Number(ratio(flatten(V[a], ground), ground).toFixed(2));
  }
  return out;
}

module.exports = { table, KINDS };

if (require.main === module) {
  table().then((t) => {
    const body = ['/* GENERATED by tools/accessibility/cvd-table.ts — do not edit. Run: npx tsx tools/accessibility/cvd-table.ts */',
      '',
      'export const CVD = ' + JSON.stringify(t, null, 2) + ';',
      '/** The ratio a sheet may print, formatted. Never type one by hand. */',
      "const ratioLabel = function (a: string, b: string): string { const ratios = CVD.ratios as Readonly<Record<string, number>>; const value = ratios[a + ' on ' + b]; return value == null ? '—' : value.toFixed(2) + ':1'; };",
      'export { ratioLabel as R };',
      ''].join('\n');
    fs.writeFileSync(path.join(__dirname, '..', '..', 'src', 'kit', 'foundations', 'cvd.generated.ts'), body);
    console.log('wrote src/kit/foundations/cvd.generated.ts');
  });
}
