/* Generate src/kit/foundations/primer.generated.ts from the pinned Primer
 * Primitives package, or verify that the committed module is current.
 *
 *   npm run tokens:generate
 *   npm run tokens:check */
'use strict';

import { generateTokens, type GeneratedTokens } from './generate.ts';

const fs = require('node:fs') as typeof import('node:fs');
const path = require('node:path') as typeof import('node:path');

const OUTPUT = path.resolve(__dirname, '..', '..', 'src', 'kit', 'foundations', 'primer.generated.ts');

const literal = function (value: unknown): string {
  return JSON.stringify(value).replace(/'/g, "\\'").replace(/"/g, "'");
};

export function formatTokenModule(tokens: GeneratedTokens): string {
  const rows = function (values: readonly unknown[]): string[] {
    return values.map((value) => '  ' + literal(value) + ',');
  };
  return [
    '/* GENERATED by tools/tokens/tokens.ts from @primer/primitives v' + tokens.version + ' (MIT, GitHub Inc.).',
    ' * Do not edit by hand. Run: npm run tokens:generate */',
    '',
    "export const PRIMER_VERSION = '" + tokens.version + "';",
    '',
    '/** [name, #RRGGBB or #RRGGBBAA, description, the Primer source it resolves to, Figma variable scopes] */',
    'export const PRIMER_COLORS = [',
    ...rows(tokens.colors.map((color) => [color.name, color.hex, color.description, color.source, color.scopes])),
    '] as const;',
    '',
    '/** Sources several installed colours resolve to, and how Primer relates them. */',
    'export const PRIMER_COLOR_SHARING = [',
    ...rows(tokens.sharing.map((entry) => [entry.source, entry.policy, entry.rationale])),
    '] as const;',
    '',
    '/** [name, value, Figma variable scopes] */',
    'export const PRIMER_SIZES = [',
    ...rows(tokens.sizes),
    '] as const;',
    '',
    '/** [role, family, size, line height in px, weight, description] */',
    'export const PRIMER_TEXT = [',
    ...rows(tokens.text),
    '] as const;',
    '',
    '/** [name, layers, description]; colours are #RRGGBBAA. */',
    'export const PRIMER_SHADOWS = [',
    ...rows(tokens.shadows),
    '] as const;',
    '',
    'export const PRIMER_MOTION = {',
    '  durations: [',
    ...rows(tokens.motion.durations).map((line) => '  ' + line),
    '  ],',
    '  easings: [',
    ...rows(tokens.motion.easings).map((line) => '  ' + line),
    '  ],',
    '  transitions: [',
    ...rows(tokens.motion.transitions).map((line) => '  ' + line),
    '  ],',
    '} as const;',
    '',
  ].join('\n');
}

if (require.main === module) {
  const source = formatTokenModule(generateTokens());
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(OUTPUT) ? fs.readFileSync(OUTPUT, 'utf8') : '';
    if (current !== source) {
      console.error('src/kit/foundations/primer.generated.ts is stale. Run: npm run tokens:generate');
      process.exit(1);
    }
    console.log('primer tokens: generated module is current');
  } else {
    const temporary = OUTPUT + '.tmp';
    fs.writeFileSync(temporary, source);
    fs.renameSync(temporary, OUTPUT);
    console.log('wrote src/kit/foundations/primer.generated.ts');
  }
}
