/* ============================================================================
 * Generates the design system's colour-vision table (its design-system.json
 * names the file): what each declared colour looks like to a reader with
 * colour-vision deficiency.
 *
 * The plugin runs inside Figma and cannot require this package's colour
 * maths, and a second Viénot reduction in the design system would mean two
 * implementations of the same physics, quietly disagreeing. So the values are
 * computed here, once, and emitted as a table. accessibility/a11y.ts
 * re-derives them on every run and fails if the table has drifted.
 * ==========================================================================*/
'use strict';

import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  flatten,
  ratio,
  simulate,
  toHex,
} from '../color/core/color.ts';
import { CVD_KINDS } from '../color/core/palette-analysis.ts';
import { colorTokenMap } from '../color/core/token-values.ts';
import type { DesignSystemContract } from '@figma-harness/contract';
import { designSystemLayout, repositoryRoot } from '../core/workspace.ts';

interface CvdColor {
  readonly a?: number;
  readonly b: number;
  readonly g: number;
  readonly r: number;
}

export type CvdColorMap = Readonly<Record<string, CvdColor>>;

export const KINDS = CVD_KINDS;

export type CvdContract = Pick<DesignSystemContract, 'cvd' | 'pageGround'>;

/** Simulate the declared colours as they appear on the design system's page;
 *  the design system also names the ratios its sheets quote. */
export async function table(colors?: CvdColorMap, contract?: CvdContract): Promise<
  Record<string, Record<string, string | number>> & {
    normal: Record<string, string>;
    ratios: Record<string, number>;
  }
> {
  let V = colors;
  let declared = contract;
  if (!V || !declared) {
    const { createHarness } = await import('../runtime/harness.ts');
    const harness = createHarness();
    declared = declared || harness.runtime.CONTRACT.designSystem;
    if (!V) {
      await harness.runtime.ensureTokens();
      V = colorTokenMap(harness.vars);
    }
  }
  const SHOW = declared.cvd.show;
  const QUOTED = declared.cvd.quoted;
  const pageColor = V[declared.pageGround];
  if (!pageColor || (pageColor.a != null && pageColor.a < 1)) {
    throw new Error('the page ground ' + declared.pageGround + ' must be an opaque colour token');
  }
  const PAGE = Object.freeze({ r: pageColor.r, g: pageColor.g, b: pageColor.b });
  const out = {} as Record<string, Record<string, string | number>> & {
    normal: Record<string, string>;
    ratios: Record<string, number>;
  };
  const shown = (token: string) => flatten(V![token], PAGE);
  for (const k of KINDS) {
    out[k] = {};
    for (const t of SHOW) if (V[t]) out[k][t] = toHex(simulate(shown(t), k));
  }
  out.normal = {};
  for (const t of SHOW) if (V[t]) out.normal[t] = toHex(shown(t));
  out.ratios = {};
  for (const [a, b] of QUOTED) {
    if (!V[a] || !V[b]) continue;
    const ground = shown(b);
    out.ratios[a + ' on ' + b] = Number(ratio(flatten(V[a], ground), ground).toFixed(2));
  }
  return out;
}

module.exports = { table, KINDS };

if (require.main === module) {
  table().then((t) => {
    const body = ['/* GENERATED by packages/harness/src/accessibility/cvd-table.ts — do not edit. Run: pnpm cvd:generate */',
      '',
      'export const CVD = ' + JSON.stringify(t, null, 2) + ';',
      '/** The ratio a sheet may print, formatted. Never type one by hand. */',
      "const ratioLabel = function (a: string, b: string): string { const ratios = CVD.ratios as Readonly<Record<string, number>>; const value = ratios[a + ' on ' + b]; return value == null ? '—' : value.toFixed(2) + ':1'; };",
      'export { ratioLabel as R };',
      ''].join('\n');
    const output = designSystemLayout().cvdTable;
    fs.writeFileSync(output, body);
    console.log('wrote ' + path.relative(repositoryRoot(), output));
  });
}
